---
-   hosts: test_group
    remote_user: ec2-user
    become: true
    
    tasks:
    
      - name: Check icmp state
        command: cat /proc/sys/net/ipv4/icmp_echo_ignore_all
        register: icmp_state
        ignore_errors: yes
        
      - name: Add icmp enabled host to hosts file
        add_host: name = "abc"      
        when: icmp_state.stdout == "0"